/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContributorInfoTag: typeof import('./src/components/ContributorInfoTag.vue')['default']
    ContributorTag: typeof import('./src/components/ContributorTag.vue')['default']
    QuestionCard: typeof import('./src/components/QuestionCard/index.vue')['default']
    QuestionNav: typeof import('./src/components/QuestionNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollCard: typeof import('./src/components/ScrollCard/index.vue')['default']
    TAffix: typeof import('tdesign-vue-next')['Affix']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TComment: typeof import('tdesign-vue-next')['Comment']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
